[project]
name="django-statictools"
version="0.1.2"
dependencies = [
  "Django",
]

[build-system]
requires = ["setuptools>=46.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {statictools = "statictools"}
